# 1. Install Alacritty 
# 	on Mac: brew install alacritty
# 	on Ubuntu: apt install alacritty
# 2. Place this alacritty.toml file in $HOME/.config/alacritty directory

# Download themes from https://github.com/catppuccin/alacritty
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

# macOS optional: Install bash with homebrew to remove annoying zsh message
# shell.program = "/opt/homebrew/bin/bash"

# Linux: just use system bash
shell.program = "/bin/bash"

[window]
title = "Salt and light of the earth"

[font]
size = 14 

[env]
TERM = "xterm-256color"

[scrolling]
multiplier = 4

[window.dimensions]
columns = 80
lines = 35

[window.padding]
x = 12
y = 8
