[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[scrolling]
multiplier = 4

[scrolling.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[scrolling.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[window.dimensions]
columns = 80
lines = 35

[window.padding]
x = 12
y = 8
